name: Build
on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "Package name of the game:"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        cache: gradle

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25c

    - name: Build module
      run: |
        chmod +x ./gradlew
        echo "Building for package: ${{ github.event.inputs.package_name }}"
        
        # Debug: Show file structure
        echo "=== File structure ==="
        find . -name "game.h" -type f
        find . -name "*.h" -path "*/cpp/*" -type f
        
        # Check original content
        echo "=== Original game.h content ==="
        find . -name "game.h" -exec cat {} \;
        
        # Update module description
        sed -i 's/moduleDescription = "/moduleDescription = "(${{ github.event.inputs.package_name }}) /g' module.gradle
        
        # Try multiple possible locations and patterns for game.h
        find . -name "game.h" -exec sed -i "s/com\.game\.packagename/${{ github.event.inputs.package_name }}/g" {} \;
        find . -name "game.h" -exec sed -i "s/com\.example\.package/${{ github.event.inputs.package_name }}/g" {} \;
        find . -name "game.h" -exec sed -i "s/GAME_PACKAGE_NAME \".*\"/GAME_PACKAGE_NAME \"${{ github.event.inputs.package_name }}\"/g" {} \;
        
        # Verify the change worked
        echo "=== Updated game.h content ==="
        find . -name "game.h" -exec cat {} \;
        
        echo "=== Module gradle ==="
        grep "moduleDescription" module.gradle || echo "moduleDescription not found"
        
        echo "=== Game header search ==="
        find . -name "game.h" -exec grep -H "GAME_PACKAGE_NAME\|package" {} \; || echo "No package references found"
        
        # Build the module
        ./gradlew :module:assembleRelease

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: zygisk-il2cppdumper-${{ github.event.inputs.package_name }}
        path: out/magisk_module_release/
        if-no-files-found: error
