name: Build
on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "Package name of the game:"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        cache: gradle

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25c
        add-to-path: false

    - name: Build module
      run: |
        chmod +x ./gradlew
        echo "Building for package: ${{ github.event.inputs.package_name }}"
        
        # Update module description
        sed -i 's/moduleDescription = "/moduleDescription = "(${{ github.event.inputs.package_name }}) /g' module.gradle
        
        # Update package name in C++ header
        sed -i "s/com\.game\.packagename/${{ github.event.inputs.package_name }}/g" module/src/main/cpp/game.h
        
        # Verify changes
        echo "=== Module gradle ===" 
        grep "moduleDescription" module.gradle || echo "moduleDescription not found"
        echo "=== Game header ==="
        grep "GAME_PACKAGE_NAME" module/src/main/cpp/game.h || echo "GAME_PACKAGE_NAME not found"
        
        # Build the module
        ./gradlew :module:assembleRelease

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: zygisk-il2cppdumper-${{ github.event.inputs.package_name }}
        path: |
          out/magisk_module_release/
          module/build/outputs/
        compression-level: 6
        if-no-files-found: error
